import type {
  Appointment,
  AppUser,
  BookingMockState,
  ClinicalRecord,
  Clinic,
  ClinicBookingSettings,
  Organization,
  Patient,
  Specialty,
  Visit,
  VisitType,
  WorkingHours,
} from "./bookingTypes";

export const BOOKING_REFERENCE_DATE = "2026-05-04";

const organization: Organization = {
  id: "org-dentalos-demo",
  name: "DentalOS Studio",
  slug: "dentalos-studio",
};

const workingHoursA: WorkingHours = {
  monday: { enabled: true, start: "08:00", end: "18:00" },
  tuesday: { enabled: true, start: "08:00", end: "18:00" },
  wednesday: { enabled: true, start: "08:00", end: "18:00" },
  thursday: { enabled: true, start: "08:00", end: "18:00" },
  friday: { enabled: true, start: "08:00", end: "17:00" },
  saturday: { enabled: true, start: "09:00", end: "14:00" },
  sunday: { enabled: false, start: "09:00", end: "13:00" },
};

const workingHoursB: WorkingHours = {
  monday: { enabled: true, start: "09:00", end: "19:00" },
  tuesday: { enabled: true, start: "09:00", end: "19:00" },
  wednesday: { enabled: true, start: "09:00", end: "19:00" },
  thursday: { enabled: true, start: "09:00", end: "19:00" },
  friday: { enabled: true, start: "09:00", end: "18:00" },
  saturday: { enabled: false, start: "09:00", end: "14:00" },
  sunday: { enabled: false, start: "09:00", end: "13:00" },
};

const clinics: Clinic[] = [
  {
    id: "clinic-central",
    orgId: organization.id,
    code: "CDV-001",
    name: "Clinica Centro",
    status: "active",
    addressText: "Av. Reforma 125, Piso 3, Ciudad de Mexico",
    phone: "+52 55 1234 5001",
    email: "centro@dentalos.mx",
  },
  {
    id: "clinic-roma",
    orgId: organization.id,
    code: "CDV-002",
    name: "Clinica Roma",
    status: "active",
    addressText: "Puebla 80, Roma Norte, Ciudad de Mexico",
    phone: "+52 55 1234 5002",
    email: "roma@dentalos.mx",
  },
];

const specialties: Specialty[] = [
  { id: "spec-general", orgId: organization.id, code: "GENERAL", name: "Odontologia general", isActive: true },
  { id: "spec-ortho", orgId: organization.id, code: "ORTHO", name: "Ortodoncia", isActive: true },
  { id: "spec-endo", orgId: organization.id, code: "ENDO", name: "Endodoncia", isActive: true },
  { id: "spec-pedia", orgId: organization.id, code: "PEDIA", name: "Odontologia pediatrica", isActive: true },
];

const visitTypes: VisitType[] = [
  { id: "vt-first", code: "FIRST_VISIT", name: "Primera valoracion", sortOrder: 1, isActive: true },
  { id: "vt-follow", code: "FOLLOW_UP", name: "Seguimiento", sortOrder: 2, isActive: true },
  { id: "vt-clean", code: "CLEANING", name: "Limpieza", sortOrder: 3, isActive: true },
];

const users: AppUser[] = [
  {
    id: "user-ana-admin",
    orgId: organization.id,
    displayName: "Ana Martinez",
    firstName: "Ana",
    lastName: "Martinez",
    email: "ana@dentalos.mx",
    status: "active",
    userCategory: "admin",
    specialtyIds: [],
  },
  {
    id: "user-lucia-reception",
    orgId: organization.id,
    displayName: "Lucia Torres",
    firstName: "Lucia",
    lastName: "Torres",
    email: "lucia@dentalos.mx",
    status: "active",
    userCategory: "reception",
    specialtyIds: [],
  },
  {
    id: "user-camila",
    orgId: organization.id,
    displayName: "Dra. Camila Ortega",
    firstName: "Camila",
    lastName: "Ortega",
    email: "camila@dentalos.mx",
    status: "active",
    userCategory: "dentist",
    specialtyIds: ["spec-general", "spec-pedia"],
  },
  {
    id: "user-diego",
    orgId: organization.id,
    displayName: "Dr. Diego Mendoza",
    firstName: "Diego",
    lastName: "Mendoza",
    email: "diego@dentalos.mx",
    status: "active",
    userCategory: "dentist",
    specialtyIds: ["spec-ortho"],
  },
  {
    id: "user-elena",
    orgId: organization.id,
    displayName: "Dra. Elena Ruiz",
    firstName: "Elena",
    lastName: "Ruiz",
    email: "elena@dentalos.mx",
    status: "active",
    userCategory: "dentist",
    specialtyIds: ["spec-endo", "spec-general"],
  },
];

const patients: Patient[] = [
  {
    id: "patient-maria",
    orgId: organization.id,
    patientCode: "PAC-001",
    firstName: "Maria",
    lastName: "Gomez",
    secondLastName: "Lopez",
    birthDate: "1991-08-14",
    phone: "+52 55 3000 1001",
    email: "maria.gomez@correo.com",
    status: "active",
    fullNameNormalized: "maria gomez lopez",
  },
  {
    id: "patient-jose",
    orgId: organization.id,
    patientCode: "PAC-002",
    firstName: "Jose",
    lastName: "Torres",
    secondLastName: "Diaz",
    birthDate: "1985-01-22",
    phone: "+52 55 3000 1002",
    email: "jose.torres@correo.com",
    status: "active",
    fullNameNormalized: "jose torres diaz",
  },
  {
    id: "patient-carolina",
    orgId: organization.id,
    patientCode: "PAC-003",
    firstName: "Carolina",
    lastName: "Vega",
    secondLastName: "Rios",
    birthDate: "1999-06-05",
    phone: "+52 55 3000 1003",
    email: "carolina.vega@correo.com",
    status: "active",
    fullNameNormalized: "carolina vega rios",
  },
  {
    id: "patient-luis",
    orgId: organization.id,
    patientCode: "PAC-004",
    firstName: "Luis",
    lastName: "Ortega",
    secondLastName: "Salas",
    birthDate: "1979-11-29",
    phone: "+52 55 3000 1004",
    email: "luis.ortega@correo.com",
    status: "active",
    fullNameNormalized: "luis ortega salas",
  },
  {
    id: "patient-sofia",
    orgId: organization.id,
    patientCode: "PAC-005",
    firstName: "Sofia",
    lastName: "Ramirez",
    secondLastName: "Mora",
    birthDate: "2012-03-18",
    phone: "+52 55 3000 1005",
    email: "sofia.ramirez@correo.com",
    status: "active",
    fullNameNormalized: "sofia ramirez mora",
  },
  {
    id: "patient-raul",
    orgId: organization.id,
    patientCode: "PAC-006",
    firstName: "Raul",
    lastName: "Medina",
    secondLastName: "Cruz",
    birthDate: "1968-09-09",
    phone: "+52 55 3000 1006",
    email: null,
    status: "inactive",
    fullNameNormalized: "raul medina cruz",
  },
];

const clinicalRecords: ClinicalRecord[] = [
  {
    id: "record-maria",
    orgId: organization.id,
    patientId: "patient-maria",
    recordNumber: "EXP-2026-001",
    status: "open",
    clinicalSummary: "Seguimiento preventivo semestral.",
    riskFlagsSummary: null,
    alertFlagsJson: [],
  },
  {
    id: "record-jose",
    orgId: organization.id,
    patientId: "patient-jose",
    recordNumber: "EXP-2026-002",
    status: "open",
    clinicalSummary: "Paciente con uso de alineadores.",
    riskFlagsSummary: "Ajustes de ortodoncia en curso.",
    alertFlagsJson: [],
  },
  {
    id: "record-carolina",
    orgId: organization.id,
    patientId: "patient-carolina",
    recordNumber: "EXP-2026-003",
    status: "archived",
    clinicalSummary: "Expediente archivado por cambio de sede.",
    riskFlagsSummary: null,
    alertFlagsJson: ["Expediente archivado"],
  },
  {
    id: "record-luis",
    orgId: organization.id,
    patientId: "patient-luis",
    recordNumber: "EXP-2026-004",
    status: "open",
    clinicalSummary: "Control de sensibilidad posterior a restauracion.",
    riskFlagsSummary: "Alergia reportada a latex.",
    alertFlagsJson: ["Alergia a latex"],
  },
  {
    id: "record-sofia",
    orgId: organization.id,
    patientId: "patient-sofia",
    recordNumber: "EXP-2026-005",
    status: "open",
    clinicalSummary: "Paciente pediatrica en control de higiene.",
    riskFlagsSummary: "Paciente menor, requiere acompanante.",
    alertFlagsJson: ["Paciente menor"],
  },
  {
    id: "record-raul",
    orgId: organization.id,
    patientId: "patient-raul",
    recordNumber: "EXP-2026-006",
    status: "open",
    clinicalSummary: "Rehabilitacion protetica en seguimiento.",
    riskFlagsSummary: "Hipertension controlada.",
    alertFlagsJson: ["Hipertension controlada"],
  },
];

const settings: ClinicBookingSettings[] = [
  {
    id: "setting-central",
    orgId: organization.id,
    clinicId: "clinic-central",
    defaultSlotDurationMinutes: 30,
    minNoticeMinutes: 30,
    maxDaysAhead: 90,
    internalBookingEnabled: true,
    externalBookingEnabled: false,
    externalRequiresManualConfirmation: true,
    workingHoursJson: workingHoursA,
    metadataJson: {},
    createdAt: "2026-04-01T08:00:00-06:00",
    updatedAt: "2026-05-01T08:00:00-06:00",
  },
  {
    id: "setting-roma",
    orgId: organization.id,
    clinicId: "clinic-roma",
    defaultSlotDurationMinutes: 45,
    minNoticeMinutes: 60,
    maxDaysAhead: 60,
    internalBookingEnabled: true,
    externalBookingEnabled: false,
    externalRequiresManualConfirmation: true,
    workingHoursJson: workingHoursB,
    metadataJson: {},
    createdAt: "2026-04-01T08:00:00-06:00",
    updatedAt: "2026-05-02T08:00:00-06:00",
  },
];

const visits: Visit[] = [
  {
    id: "visit-001",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-sofia",
    clinicalRecordId: "record-sofia",
    createdByUserId: "user-lucia-reception",
    attendingUserId: "user-camila",
    specialtyId: "spec-pedia",
    visitTypeId: "vt-clean",
    reasonForVisit: "Limpieza de control",
    startedAt: "2026-05-04T08:10:00-06:00",
    endedAt: "2026-05-04T08:40:00-06:00",
    status: "completed",
    sourceType: "appointment",
    createdAt: "2026-05-04T08:00:00-06:00",
    updatedAt: "2026-05-04T08:40:00-06:00",
  },
  {
    id: "visit-002",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-maria",
    clinicalRecordId: "record-maria",
    createdByUserId: "user-lucia-reception",
    attendingUserId: "user-camila",
    specialtyId: "spec-general",
    visitTypeId: "vt-follow",
    reasonForVisit: "Revision posterior a limpieza",
    startedAt: "2026-05-03T13:05:00-06:00",
    endedAt: "2026-05-03T13:30:00-06:00",
    status: "completed",
    sourceType: "appointment",
    createdAt: "2026-05-03T12:50:00-06:00",
    updatedAt: "2026-05-03T13:30:00-06:00",
  },
];

const appointments: Appointment[] = [
  {
    id: "appt-001",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-maria",
    clinicalRecordId: "record-maria",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-lucia-reception",
    attendingUserId: "user-camila",
    specialtyId: "spec-general",
    visitTypeId: "vt-first",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "scheduled",
    scheduledStartAt: "2026-05-04T09:00:00-06:00",
    scheduledEndAt: "2026-05-04T09:30:00-06:00",
    reasonForVisit: "Valoracion por sensibilidad",
    patientNotes: "Prefiere turno temprano.",
    internalNotes: "Confirmar si requiere radiografia.",
    confirmedAt: null,
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-03T16:10:00-06:00",
    updatedAt: "2026-05-03T16:10:00-06:00",
  },
  {
    id: "appt-002",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-jose",
    clinicalRecordId: "record-jose",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-ana-admin",
    attendingUserId: "user-diego",
    specialtyId: "spec-ortho",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "confirmed",
    scheduledStartAt: "2026-05-04T09:30:00-06:00",
    scheduledEndAt: "2026-05-04T10:00:00-06:00",
    reasonForVisit: "Ajuste de alineadores",
    patientNotes: null,
    internalNotes: "Traer placa de control.",
    confirmedAt: "2026-05-03T18:00:00-06:00",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-02T15:00:00-06:00",
    updatedAt: "2026-05-03T18:00:00-06:00",
  },
  {
    id: "appt-003",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-luis",
    clinicalRecordId: "record-luis",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-lucia-reception",
    attendingUserId: "user-elena",
    specialtyId: "spec-endo",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "confirmed",
    scheduledStartAt: "2026-05-04T10:15:00-06:00",
    scheduledEndAt: "2026-05-04T11:00:00-06:00",
    reasonForVisit: "Revision posterior a endodoncia",
    patientNotes: "Llega acompanado.",
    internalNotes: "Sala 2 lista.",
    confirmedAt: "2026-05-03T19:20:00-06:00",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-02T11:00:00-06:00",
    updatedAt: "2026-05-04T10:04:00-06:00",
  },
  {
    id: "appt-004",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-sofia",
    clinicalRecordId: "record-sofia",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-camila",
    attendingUserId: "user-camila",
    specialtyId: "spec-pedia",
    visitTypeId: "vt-clean",
    visitId: "visit-001",
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "completed",
    scheduledStartAt: "2026-05-04T08:00:00-06:00",
    scheduledEndAt: "2026-05-04T08:30:00-06:00",
    reasonForVisit: "Limpieza y control infantil",
    patientNotes: "Asiste con su mama.",
    internalNotes: null,
    confirmedAt: "2026-05-03T17:20:00-06:00",
    checkedInAt: "2026-05-04T07:55:00-06:00",
    completedAt: "2026-05-04T08:40:00-06:00",
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-01T12:30:00-06:00",
    updatedAt: "2026-05-04T08:40:00-06:00",
  },
  {
    id: "appt-005",
    orgId: organization.id,
    clinicId: "clinic-roma",
    patientId: "patient-raul",
    clinicalRecordId: "record-raul",
    createdByUserId: "user-ana-admin",
    updatedByUserId: "user-ana-admin",
    attendingUserId: "user-diego",
    specialtyId: "spec-ortho",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "cancelled",
    scheduledStartAt: "2026-05-04T11:30:00-06:00",
    scheduledEndAt: "2026-05-04T12:15:00-06:00",
    reasonForVisit: "Control de ajuste",
    patientNotes: null,
    internalNotes: "Paciente solicito reagendar despues.",
    confirmedAt: null,
    checkedInAt: null,
    completedAt: null,
    cancelledAt: "2026-05-04T09:10:00-06:00",
    cancelledByUserId: "user-ana-admin",
    cancellationReason: "Paciente viaja fuera de la ciudad.",
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-01T14:10:00-06:00",
    updatedAt: "2026-05-04T09:10:00-06:00",
  },
  {
    id: "appt-006",
    orgId: organization.id,
    clinicId: "clinic-roma",
    patientId: "patient-raul",
    clinicalRecordId: "record-raul",
    createdByUserId: "user-ana-admin",
    updatedByUserId: "user-lucia-reception",
    attendingUserId: "user-elena",
    specialtyId: "spec-general",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "no_show",
    scheduledStartAt: "2026-05-04T14:00:00-06:00",
    scheduledEndAt: "2026-05-04T14:30:00-06:00",
    reasonForVisit: "Revision de protesis",
    patientNotes: null,
    internalNotes: "Llamar para seguimiento.",
    confirmedAt: "2026-05-03T13:00:00-06:00",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: "2026-05-04T14:25:00-06:00",
    noShowMarkedByUserId: "user-lucia-reception",
    noShowReason: "No contesto llamadas de recepcion.",
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-02T13:10:00-06:00",
    updatedAt: "2026-05-04T14:25:00-06:00",
  },
  {
    id: "appt-007",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-luis",
    clinicalRecordId: "record-luis",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-ana-admin",
    attendingUserId: "user-elena",
    specialtyId: "spec-endo",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "rescheduled",
    scheduledStartAt: "2026-05-03T16:00:00-06:00",
    scheduledEndAt: "2026-05-03T16:30:00-06:00",
    reasonForVisit: "Molestia posterior a tratamiento",
    patientNotes: null,
    internalNotes: "Paciente pidio mover a manana.",
    confirmedAt: "2026-05-02T17:40:00-06:00",
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: "INT-REBOOK-001",
    metadataJson: {},
    createdAt: "2026-05-01T15:00:00-06:00",
    updatedAt: "2026-05-03T10:30:00-06:00",
  },
  {
    id: "appt-008",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-luis",
    clinicalRecordId: "record-luis",
    createdByUserId: "user-ana-admin",
    updatedByUserId: "user-ana-admin",
    attendingUserId: "user-elena",
    specialtyId: "spec-endo",
    visitTypeId: "vt-follow",
    visitId: null,
    rescheduledFromAppointmentId: "appt-007",
    bookingSource: "internal",
    status: "scheduled",
    scheduledStartAt: "2026-05-05T16:00:00-06:00",
    scheduledEndAt: "2026-05-05T16:30:00-06:00",
    reasonForVisit: "Molestia posterior a tratamiento",
    patientNotes: null,
    internalNotes: "Nueva fecha por solicitud del paciente.",
    confirmedAt: null,
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-03T10:30:00-06:00",
    updatedAt: "2026-05-03T10:30:00-06:00",
  },
  {
    id: "appt-009",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-maria",
    clinicalRecordId: "record-maria",
    createdByUserId: "user-lucia-reception",
    updatedByUserId: "user-camila",
    attendingUserId: "user-camila",
    specialtyId: "spec-general",
    visitTypeId: "vt-follow",
    visitId: "visit-002",
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "completed",
    scheduledStartAt: "2026-05-03T13:00:00-06:00",
    scheduledEndAt: "2026-05-03T13:30:00-06:00",
    reasonForVisit: "Revision posterior a limpieza",
    patientNotes: null,
    internalNotes: null,
    confirmedAt: "2026-05-02T18:10:00-06:00",
    checkedInAt: "2026-05-03T12:58:00-06:00",
    completedAt: "2026-05-03T13:30:00-06:00",
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-01T09:00:00-06:00",
    updatedAt: "2026-05-03T13:30:00-06:00",
  },
  {
    id: "appt-010",
    orgId: organization.id,
    clinicId: "clinic-central",
    patientId: "patient-carolina",
    clinicalRecordId: "record-carolina",
    createdByUserId: "user-ana-admin",
    updatedByUserId: null,
    attendingUserId: null,
    specialtyId: "spec-general",
    visitTypeId: "vt-first",
    visitId: null,
    rescheduledFromAppointmentId: null,
    bookingSource: "internal",
    status: "draft",
    scheduledStartAt: "2026-05-06T14:00:00-06:00",
    scheduledEndAt: "2026-05-06T14:30:00-06:00",
    reasonForVisit: "Revision inicial",
    patientNotes: "Paciente nueva en la sede.",
    internalNotes: "Bloqueada hasta validar expediente activo.",
    confirmedAt: null,
    checkedInAt: null,
    completedAt: null,
    cancelledAt: null,
    cancelledByUserId: null,
    cancellationReason: null,
    noShowMarkedAt: null,
    noShowMarkedByUserId: null,
    noShowReason: null,
    externalReference: null,
    metadataJson: {},
    createdAt: "2026-05-03T11:25:00-06:00",
    updatedAt: "2026-05-03T11:25:00-06:00",
  },
];

const baseState: BookingMockState = {
  organization,
  currentUserId: "user-ana-admin",
  clinics,
  patients,
  clinicalRecords,
  users,
  specialties,
  visitTypes,
  appointments,
  visits,
  settings,
};

export function createInitialBookingState(): BookingMockState {
  return structuredClone(baseState);
}
